#!/bin/bash
set -e
source ./schema.properties
if [[ $1 = "all" ]] ; then
	echo "Deleting all data"
	MYSQL_PWD=$password mysql -u$username  -h$dbHost -P$mysqlPort $db -e "truncate table1"
	MYSQL_PWD=$password mysql -u$username  -h$dbHost -P$mysqlPort $db -e "truncate table2"
else
	echo "Deleting benchmark data"
	MYSQL_PWD=$password mysql -u$username  -h$dbHost -P$mysqlPort $db -e "delete from table1 where id < 1000000"
	MYSQL_PWD=$password mysql -u$username  -h$dbHost -P$mysqlPort $db -e "delete from table2 where id < 1000000"
fi

