#!/bin/bash
set -e
source ./setup
if [[ $1 = "all" ]] ; then
	echo "Deleting all data"
	MYSQL_PWD=$password mysql -u$username  -h$dbHost -P$mysqlPort $db -e "truncate test"
else
	echo "Deleting benchmark data"
	MYSQL_PWD=$password mysql -u$username  -h$dbHost -P$mysqlPort $db -e "delete from test where id < 1000000"
fi

