#!/bin/bash
java -Xmx20G  -XX:MaxDirectMemorySize=1000m -jar ../target/clusterj-ndb-micro-benchmark-1.0-jar-with-dependencies.jar -schema test -dbHost cloud1.sics.se -rowPerTx 1 -numThreads 1 -microBenchType PK  -clientId 0
