#!/bin/bash

set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
user=tester
hosts="hadoop2 hadoop3 hadoop4 hadoop6 hadoop36"

tests=(pk batch ppis is fts)
path="/home/tester/salman/clusterj-ndb-micro-bench/scripts"

for ((run=1; run<=3;run++))
do
	for ((thread=1; thread<=100;))
	do

		for test in ${tests[@]}
		do
			pssh -H "$hosts" -l $user "sed -i 's#numThreads=.*#numThreads=$thread#g' $DIR/setup" 
			pssh -H "$hosts" -l $user "sed -i 's#runNumber=.*#runNumber=$run#g' $DIR/setup" 
			echo "Running test $test for thread count $thread run number $run" 
			pssh -H "$hosts" -l $user -i -t 600 "bash $DIR/$test " 
		done
		if [[ $thread = 1 ]]; then
			thread=2;
		else
			thread=$(echo "$thread+2" | bc)
		fi
	done
done
